### ISSUE TITLE
auto_add_role_name description is incorrect.

### ISSUE THREAD

**Issue by ReComposer** [skytap/terraform-provider-skytap#12]
The description of `auto_add_role` is incorrect. (Note that this is also being updated in the Skytap API docs.)

The revised text is:

(Optional) If this field is set to `viewer`, `participant`, `editor`, or `manager`, new users added to your account are automatically added to this project with the specified project role. Existing users aren’t affected by this setting. If the field is set to `null`, new users aren’t automatically added to the project. For additional details, see [Automatically adding new users to a project](https://help.skytap.com/csh-project-automatic-role.html.).

**Comment by pegerto** [comment]
Hi, @ReComposer will you PR to update this documentation?
