### ISSUE TITLE
Add unique User-Agent when making calls to Skytap API

### ISSUE THREAD

**Issue by loketan-zz** [skytap/terraform-provider-skytap#26]
In order to track incoming calls to Skytap via the Terraform provider, we need a method for the provider to send a unique identifier in the `User-Agent` string. You could use the identifier "tf-"+version (eg. `tf-1.0.0`)

**Comment by pegerto** [comment]
Hello Loke,

We will need to provide some version information, but the SDK support the replacement of the user agent.

**Comment by ja6a** [comment]
Addressed under PR #40. At present the version will be hard coded in a file called `version.go`. This will facilitate extension at a later date whereby the build script can be made to read the current version and write to this file.

**Comment by ja6a** [comment]
The user agent is `terraform-provider-skytap`. The entire user agent string will be `terraform-provider-skytap/2.0.0`

**Comment by lokeuei** [comment]
looks good. thanks!

**Comment by lokeuei** [comment]
@ja6a btw, does this user agent string flow through the SDK? eg. the SDK's user agent string is `skytap-go-sdk`, will the resulting user-agent string to the API look like `terraform-provider-skytap/2.0.0/skytap-go-sdk` ?

**Comment by ja6a** [comment]
The user agent supplied by the terraform provider is intended to overwrite the one supplied by the SDK. E.g. when terraform provider is used I would expect `terraform-provider-skytap/1.11.1`. When the SDK is used alone I would expect `skytap-sdk-go/1.0.0`

**Comment by loketan-zz** [comment]
ah, even better. thanks James.

regards,

*________________________________*
*Loke Tan* | Director, Product Management

m: +1 425-223-8802
<(425)%20223-8802>
 e: ltan@skytap.com

**Comment by thewellington** [comment]
resolved in v0.11.1
