### ISSUE TITLE
Environment support tags and labels from terraform.

### ISSUE THREAD

**Issue by loketan-zz** [skytap/terraform-provider-skytap#31]
Ability to add tags to environments when creating environments via Terraform. Currently it is not an option per the following documentation.

https://www.terraform.io/docs/providers/skytap/r/environment.html

**Comment by pegerto** [comment]
Hello @loketan 

My understanding is that we model this using a set,  the expectation is to trim the value and make the hash function for the test not case sensitive, as result, we should have the same behaviour of no-case-sensitive value as the Skytap API implements.

API support and documentation for the V2 API: https://help.skytap.com/API_v2_Documentation.html#EnvTags, 

SDK requires modifications to support this functionality.

**Comment by pegerto** [comment]
The following PRs are related to this requirement #52 #53
