### ISSUE TITLE
Gracefully handle Skytap's REST API status codes

### ISSUE THREAD

**Issue by thewellington** [skytap/terraform-provider-skytap#34]
### Terraform Version
11.13

### Affected Resource(s)
Skytap's API is pretty good about returning status codes and error messages for every API call.  Handling these calls throughout the product instead of simply retrying and timing out would allow end users to effectively determine where things have gone wrong.

### References
- https://help.skytap.com/api-http-status-codes.html
- https://help.skytap.com/api-busy-bp.html

**Comment by ja6a** [comment]
This work was covered under #33 and PR #41 .

The behaviour is described in the ticket #33 but the status code logic is recapped here:
1. 200: is considered a successful request and polling occurs until the state is as expected.
2. 409, 422, 423, 429: the request is retried. An error is extracted if present. The wait time is 10 seconds unless prescribed in the response.
3. all other status codes are considered as errors.
4. a 422 error other than busy will be considered as an error.

**Comment by ja6a** [comment]
The terraform provider now has reduced logging for most output, i.e. at INFO level. The verbose output has been demoted to trace level.

**Comment by thewellington** [comment]
This issue is resolved in v.0.11.1
