### ISSUE TITLE
RAM invalid key - CPU too

### ISSUE THREAD

**Issue by thewellington** [skytap/terraform-provider-skytap#35]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
terraform -v
Terraform v0.11.13
+ provider.skytap v0.9.0

Your version of Terraform is out of date! The latest version
is 0.12.1. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- skytap_vm

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "skytap_vm" "webservers" {
  # Add some VMs to the environment
  count = "${var.vm_count}"
  template_id = "1599587"  ## This is a Centos 75 Template in my account - it has no nic and no network
  vm_id = "45214703"
  environment_id = "${skytap_environment.environment.id}"
  name = "web-${count.index}"
  ram = "4096"
  cpus = "3"
}
```

### Expected Behavior
I should have gotten a VM with 3 CPUs and 4 Gigs of RAM

### Actual Behavior
I got errors:

`Error: skytap_vm.webservers: : invalid or unknown key: ram`
`Error: skytap_vm.webservers: : invalid or unknown key: cpus`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by ja6a** [comment]
You will need to manually build your own binary from master. On our side we will soon be releasing the latest code.

**Comment by ja6a** [comment]
I will close this once the release is done.

**Comment by ja6a** [comment]
This is a non-issue. I have tested it with the latest 0.10.0 release and it works as expected.
