### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [skytap/terraform-provider-skytap#52]
Hi Team,

My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. 

 - [x] When building the provider binary with go1.11, I've continued to have compile error, Im still confused at why this error is happening because those methods are clearly defined in skytap/utils/untils.go. Hopefully you have a solution for this issue. 
```
$ make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
# github.com/terraform-providers/terraform-provider-skytap/skytap
skytap/resource_skytap_network.go:79:16: undefined: utils.NetworkType
skytap/resource_skytap_vm.go:151:15: undefined: utils.NICType
skytap/resource_skytap_vm.go:285:19: undefined: utils.VMRunstate
make: *** [test] Error 1
```

The website documentation looks great, but there are a few changes that must be address.
- [x] In provider.go the arguments the `api_token` element is defined as "Optional" in the code and "Required" in the documentation. 
- [x] resource_skytap_environment.go defines arguments `name` and `description as` "Required" but they are listed as "Optional" in the docs.   As well the `owner` argument is commented out and should be removed from the code base before the release. 
- [x] resource_skytap_network.go defines `domain` and `subnet` as "Required" and they are listed as "Optional" in the docs.

I am also going to include this list of Terraform Provider Code Expectations/Conventions that has been defined by our Terraform Engineering team, follow these closely and it will help greatly to speed up the technical review process:

 - [x] resource filename matches convention `resource_providername_resource_name.go`
 - [x] data source filename matches convention `data_source_providername_resource_name.go`
 - [x] we always let `d.Set()` to dereference pointers safely to avoid crashes, i.e. there's nothing like `d.Set(*variable)`
 - [x] flatteners and expanders are in `structures.go` + tests in `structures_test.go`
 - [x] any validation functions longer than a few lines are in `validators.go` + tests in `validators_test.go`
 - [x] `d.Set()` is called in any C/R/U/D for all available fields unless they're Computed-only (i.e. there are no orphans)
 - [x] all of `d.Set()`, `d.Get()`, `d.GetOk()`, `d.GetChange()` etc. use real field names (i.e. no typos)
 - [x] `d.Set()` is _always_ error-checked if it’s set, list or map
 - [x] `d.Set()` is _never_ error-checked if it's primitive data type (string, int, float, bool)
 - [x] Resource uses either `Read` or `Exists` function to remove resource from state if it's gone
 - [x] `d.Partial()` & `d.SetPartial()` are used any time there's more than 1 API call used to create or update a resource.
 - [x] `schema.ForceNew` is used for any field that is not updatable
 - [x] all field names are `lowercase_underscore`
 - [x] where possible data source fields match resource (e.g. when referencing `aws_instance` user shouldn't need to change anything - just add `data.` prefix)
 - [x] Constants are used if there are available in the upstream SDK (e.g. for status codes)
 - [x] `[INFO]` log message at least 2 per each C/R/U/D - e.g. creating (input), created (output)
 - [x] The provider code does not `panic`, always returns errors

Thanks you for building this provider and I look forward to getting it released officially! Let me know if you have any questions.

Best,
Chris

**Comment by pegerto** [comment]
Hi @cgriggs01

Thank you very much for the quick updated, we will start to address this issues immediately. I will update this ticket as soon it's ready to review.

I expect to have this comments remediated in 2 days.

Thanks

**Comment by pegerto** [comment]
Hello @cgriggs01 

I am not sure about the error in `make test`, we do run `make test` for every pull in Travis with a  go1.11 image

Can you attach more information, about your set up,  just to replicate where you are? For example:

```
cat .git/refs/heads/master
go version 
go env
```

Regards.

**Comment by cgriggs01** [comment]
Hi @pegerto,

Yeah i can share that. The git commit tag is `f6888960991539042c1bdf252b0efc855b44f418`, I am running `go1.11` and the go env is as follow:
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hashibook/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hashibook/Repository"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bf/6n0whcjn2x17rp19q0yc2vfc0000gn/T/go-build658039641=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
Let me know if you need anything else.

Best,
Chris

**Comment by pegerto** [comment]
Hello @cgriggs01 

I still unable to reproduce your issue with the unexported function, please try to update to master and run `go clean -cache`. And we will focus or effort to find out why if this still a blocker.

This last 2 working days, we have updated the documentation and we have refactored the code as per the engineering check-list.

Please advice in the next steps in terms of code review, etc.

Regards.
Pegerto F.

**Comment by nickithewatt** [comment]
@cgriggs01, just wondering if there is a timeline for the next stage of the review, we believe code, tests, docs are all ready and in place for you now :)
Thanks

**Comment by cgriggs01** [comment]
Hi @nickithewatt, I will run the tests again, once those are all passing The next step will be a review from an engineer from the Terraform engineering team. They are currently working to review other provider but your will be the second in the queue for technical review. I expect that the the technical review will begin in after the Thanksgiving holiday. After that, we'll be ready to certify and release the provider. 

Let me know if you have any questions.

**Comment by cgriggs01** [comment]
@nickithewatt, I misspoke in my previous comment. The provider has already passed initial review and is fist in line to be review by the ecosystem engineering team. 

This next review will most likely start the week after the Thanksgiving holiday. Thank you for your patience.

**Comment by pegerto** [comment]
Hi @cgriggs01 

Thank you for your update in the status, looking forward to the next review, please let us know if there is something help with.

Regards.

**Comment by nickithewatt** [comment]
Thanks very much @cgriggs01!

**Comment by cgriggs01** [comment]
Looking forward to releasing this provider with you'll!

I will now close this issue and my engineering colleague will open a separate issue for their review. 

Best,
Chris
