### ISSUE TITLE
Update and improve documentation as per Hashicorp review

### ISSUE THREAD

**Issue by pegerto** [skytap/terraform-provider-skytap#53]
Update the documentation as per Hashicorp review #52 

The website documentation looks great, but there are a few changes that must be addressed:

  In provider.go the arguments the api_token element is defined as "Optional" in the code and "Required" in the documentation.

  resource_skytap_environment.go defines arguments name and description as "Required" but they are listed as "Optional" in the docs. As well the owner argument is commented out and should be removed from the code base before the release.

  resource_skytap_network.go defines domain and subnet as "Required" and they are listed as "Optional" in the docs.

**Comment by ja6a** [comment]
> Update the documentation as per Hashicorp review #52
> 
> The website documentation looks great, but there are a few changes that must be addressed:
> 
> In provider.go the arguments the api_token element is defined as "Optional" in the code and "Required" in the documentation.
Done
> 
> resource_skytap_environment.go defines arguments name and description as "Required" but they are listed as "Optional" in the docs. As well the owner argument is commented out and should be removed from the code base before the release.
Done
> 
> resource_skytap_network.go defines domain and subnet as "Required" and they are listed as "Optional" in the docs.
Done
