### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by bill-rich** [skytap/terraform-provider-skytap#65]
Hello! 

My name is Bill, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit  bfce17e8b0096c791ea07f5de4d387645532df07.

- [x] Required attributes should be grouped at the top of the resource or documentation followed by the optional attributes.

- [x] When using TypeInt, setting default to `nil`, is going to result in the value being `0` when it is read. Better to keep this consistent in the schema so there isn't confusion later.

- [x] `project_id` in `skytap_environment` isn't being read or updated, but is also not `ForceNew`. This could lead to being out of sync with with actual environment and confusing diffs. 

- [x] Make sure that any attributes that aren't set in Read function are set in import function or they will remain empty.

- [x] Most resources are missing acceptance tests for importing.

- [x] For the `skytap_project` resource, the import test for project can be included in resource file instead of being split out.

- [x] Group standard libraries in imports

- [x] In `skytap_vm`, `network_interface` & `network_interface.published_service` are currently TypeList. If the order of these could change in the API response, you should use TypeSet. Otherwise changes in order will result in unnecessary diffs.

- [x] Not a big deal, but naming `vm:update` function something more descriptive would be good to avoid confusion or naming conflicts in the future.

- [x] Leave off <br/> line breaks in documentation

- [x] In the documentation, you can leave arguments off the attributes section.

- [x] The README is missing the `Using the provider` section and still has `Fill in for each provider`.

- [x] CHANGELOG.md should include information on what will be included in the initial release.

- [x] Reading test variables from environment variables instead of hardcoding them will make it easier to keep tests working smooth if the the testing environment changes in the future. See [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine_test.go#L2865-L2871) and [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine_test.go#L4243) for examples.

Overall, things look great. There are just these few items that I wanted to bring up to improve consistency with other providers, and hopefully make things a little easier.

Cheers,
Bill

**Comment by pegerto** [comment]
Hello @bill-rich 

Thank you,  very much for the review, we are starting today to address this issue, will probably have address most of the issues by the end of today.

Regards.

**Comment by bill-rich** [comment]
@pegerto That'll be great! Let me know when its ready to go and I'll give it another look.

I also wanted to apologize for the incorrect provider name in my comment originally. I combined two names I'd been working with recently.

**Comment by bill-rich** [comment]
Thanks for your understanding!

That is totally fine if you do not support importing right off. I just wanted to make sure that if it was supported, that there were acceptance tests to go with it.

**Comment by pegerto** [comment]
Hello @bill-rich 

PRs #67 and #66  address the concerns on this ticket and include some additional fix captured during the review.


Thanks again for the review and the good recommendations you raised. Let us know if there is something else we should consider, and we will work on it.

Regards,
Pegerto F.

**Comment by pegerto** [comment]
Hi @bill-rich 

I wonder if you had the chance to look at this review. 
Thank you.

**Comment by bill-rich** [comment]
@pegerto The changes look good. Thanks for getting these addressed!

**Comment by pegerto** [comment]
@bill-rich Thank for your review,

**Comment by pegerto** [comment]
Hello @bill-rich 

Can you advise in the next steps to move forward?

**Comment by pegerto** [comment]
Hello @bill-rich 

I have an answer back from Chirs, I am closing this issue, thank you very much for your review.

**Comment by night0wl** [comment]
Hi @bill-rich,

After changing network_interfaces and published_services from TypeList to TypeSet, we're having trouble figuring out the right way to interpolate these. I.e. before we could reference the indexes with something like `network_interface.0.published_service.0.external_ip`.

Can you point us in the right direction of what we should be doing to manipulate these? We've tried using matchkeys, but without success
